blank_issues_enabled: false
contact_links:
  - name: Preguntas y discusiones
    url: https://github.com/fvalenzuela-dev/movil_home_pay/discussions
    about: Usá las discusiones para preguntas, no los issues
