name: Central Validation

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  verificar_version:
    name: Control de Versiones
    uses: fvalenzuela-dev/.github/.github/workflows/version-check-new.yml@main
    with:
      version_file: "pubspec.yaml"
      base_branch: "main"
    secrets:
      GITHUB_TOKEN_CUSTOM: ${{ secrets.GITHUB_TOKEN }}
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.7'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Fix coverage path
        run: |
          mkdir -p coverage
          if [ -f "coverage/lcov.info" ]; then
            cp coverage/lcov.info coverage/lcov.info
          elif [ -f ".dart_tool/coverage/lcov.info" ]; then
            cp .dart_tool/coverage/lcov.info coverage/lcov.info
          fi
          ls -la coverage/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
          retention-days: 1

  codacy_coverage:
    name: Codacy Coverage
    needs: [build_and_test]
    uses: fvalenzuela-dev/.github/.github/workflows/codacy-coverage.yml@main
    with:
      coverage_report_path: "coverage/lcov.info"
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
